import {
  parseRunId,
  type Principal,
  type Region,
  type Result,
  type RunId,
  type SubjectId,
} from "@custodian/domain-primitives";
import type { LoopLimits } from "@custodian/agent-loop";
import type { DeploymentLabel } from "@custodian/config-registry";
import { verifyTenantClaim, type ClaimVerifier } from "@custodian/knowledge-base";
import type { TaskClass } from "@custodian/tool-registry";
import type { AgentAnswer, AgentRunFailure, AgentRunRequest } from "../application/run-agent";

export type HandlerDeps = {
  readonly run: (request: AgentRunRequest) => Promise<Result<AgentAnswer, AgentRunFailure>>;
  readonly verifier: ClaimVerifier;
  readonly now: () => Date;
  readonly principal: Principal;
  readonly subject: SubjectId;
  readonly tenantRegion: Region;
  readonly legalBasisPolicy: string;
  readonly requiresZeroRetention: boolean;
  readonly deployment: DeploymentLabel;
  readonly taskClass: TaskClass;
  readonly limits: LoopLimits;
  readonly maxOutputTokens: number;
  readonly jitter: number;
};

/** Article 50: disclosure travels in the interaction surface itself, at first contact. */
const DISCLOSURE = "Answers are generated by an AI system.";
const CLAIM_COPY = "This workspace credential is invalid or expired.";

const RUN_ID_ALPHABET = "0123456789abcdefghjkmnpqrstvwxyz";

function generateRunId(): RunId {
  const bytes = new Uint8Array(26);
  crypto.getRandomValues(bytes);
  let id = "r_";
  for (const byte of bytes) {
    id += RUN_ID_ALPHABET[byte % 32] ?? "0";
  }
  const parsed = parseRunId(id);
  if (!parsed.ok) {
    // A generated identifier failing its own grammar is programmer error, not a runtime state.
    throw new Error("generated run id failed its own grammar");
  }
  return parsed.value;
}

function json(status: number, value: Record<string, unknown>): Response {
  return new Response(JSON.stringify(value), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

/**
 * Parse → verify → delegate → map, nothing else: this layer owns HTTP shape and user-facing copy,
 * never behavior. A halted run answers 200 with its copy — the run completed and left evidence;
 * only a refusal is a client-visible 4xx.
 */
export function runsHandler(deps: HandlerDeps): (request: Request) => Promise<Response> {
  return async (request) => {
    if (request.method !== "POST") {
      return json(405, { error: "Use POST." });
    }
    const claimHeader = request.headers.get("x-tenant-claim");
    if (claimHeader === null) {
      return json(401, { error: CLAIM_COPY });
    }
    const claim = verifyTenantClaim(claimHeader, { verifier: deps.verifier, now: deps.now() });
    if (!claim.ok) {
      return json(401, { error: CLAIM_COPY });
    }

    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return json(400, { error: "Send a JSON body with a question." });
    }
    if (
      !isRecord(body) ||
      typeof body["question"] !== "string" ||
      body["question"].length === 0 ||
      body["question"].length > 4000
    ) {
      return json(400, { error: "Send a JSON body with a question." });
    }

    const runId = generateRunId();
    const outcome = await deps.run({
      runId,
      principal: deps.principal,
      claim: claim.value,
      tenantRegion: deps.tenantRegion,
      legalBasisPolicy: deps.legalBasisPolicy,
      requiresZeroRetention: deps.requiresZeroRetention,
      question: body["question"],
      subject: deps.subject,
      deployment: deps.deployment,
      taskClass: deps.taskClass,
      limits: deps.limits,
      maxOutputTokens: deps.maxOutputTokens,
      at: () => deps.now().toISOString(),
      jitter: deps.jitter,
    });

    if (!outcome.ok) {
      return json(outcome.error.kind === "refused" ? 422 : 200, {
        runId: String(runId),
        error: outcome.error.publicReason,
        disclosure: DISCLOSURE,
      });
    }
    return json(200, {
      runId: String(outcome.value.runId),
      answer: outcome.value.answer,
      disclosure: DISCLOSURE,
    });
  };
}
