import {
  generateRunId,
  isRecord,
  type Principal,
  type Region,
  type Result,
  type SubjectId,
} from "@custodian/domain-primitives";
import type { LoopLimits } from "@custodian/agent-loop";
import type { DeploymentLabel } from "@custodian/config-registry";
import { verifyTenantClaim, type ClaimVerifier } from "@custodian/knowledge-base";
import type { TaskClass } from "@custodian/tool-registry";
import type { AgentAnswer, AgentRunFailure, AgentRunRequest } from "../application/agent-run";

export type HandlerDeps = {
  readonly run: (request: AgentRunRequest) => Promise<Result<AgentAnswer, AgentRunFailure>>;
  readonly verifier: ClaimVerifier;
  readonly now: () => Date;
  readonly principal: Principal;
  readonly subject: SubjectId;
  readonly tenantRegion: Region;
  readonly legalBasisPolicy: string;
  readonly requiresZeroRetention: boolean;
  readonly deployment: DeploymentLabel;
  readonly taskClass: TaskClass;
  readonly limits: LoopLimits;
  readonly maxOutputTokens: number;
  readonly jitter: number;
};

/** Article 50: disclosure travels in the interaction surface itself, at first contact. */
const DISCLOSURE = "Answers are generated by an AI system.";
const CLAIM_COPY = "This workspace credential is invalid or expired.";

const STATUS_FOR: Readonly<Record<AgentRunFailure["kind"], number>> = {
  halted: 200,
  refused: 422,
  "already-served": 409,
  failed: 500,
};

function json(status: number, value: Record<string, unknown>): Response {
  return new Response(JSON.stringify(value), {
    status,
    headers: { "content-type": "application/json" },
  });
}

/**
 * Parse → verify → delegate → map, nothing else: this layer owns HTTP shape and user-facing copy,
 * never behavior. A halted run answers 200 with its copy — the run completed and left evidence;
 * only a refusal is a client-visible 4xx.
 */
export function runsHandler(deps: HandlerDeps): (request: Request) => Promise<Response> {
  return async (request) => {
    if (request.method !== "POST") {
      return json(405, { error: "Use POST." });
    }
    const claimHeader = request.headers.get("x-tenant-claim");
    if (claimHeader === null) {
      return json(401, { error: CLAIM_COPY });
    }
    const claim = verifyTenantClaim(claimHeader, { verifier: deps.verifier, now: deps.now() });
    if (!claim.ok) {
      return json(401, { error: CLAIM_COPY });
    }

    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return json(400, { error: "Send a JSON body with a question." });
    }
    if (
      !isRecord(body) ||
      typeof body["question"] !== "string" ||
      body["question"].length === 0 ||
      body["question"].length > 4000
    ) {
      return json(400, { error: "Send a JSON body with a question." });
    }

    const runId = generateRunId();
    const outcome = await deps.run({
      runId,
      principal: deps.principal,
      claim: claim.value,
      tenantRegion: deps.tenantRegion,
      legalBasisPolicy: deps.legalBasisPolicy,
      requiresZeroRetention: deps.requiresZeroRetention,
      question: body["question"],
      subject: deps.subject,
      deployment: deps.deployment,
      taskClass: deps.taskClass,
      limits: deps.limits,
      maxOutputTokens: deps.maxOutputTokens,
      at: () => deps.now().toISOString(),
      jitter: deps.jitter,
    });

    if (!outcome.ok) {
      // A halted run completed and left evidence, so it answers 200 with its explanation. A
      // refusal is the caller's boundary, a redelivery is a conflict, and anything else is our
      // fault — reporting those as 200 would leave a monitor watching a green error rate.
      return json(STATUS_FOR[outcome.error.kind], {
        runId: String(runId),
        error: outcome.error.publicReason,
        disclosure: DISCLOSURE,
      });
    }
    return json(200, {
      runId: String(outcome.value.runId),
      answer: outcome.value.answer,
      disclosure: DISCLOSURE,
    });
  };
}
