#!/usr/bin/env bun
/**
 * export.ts — Emit design.json as CSS vars / SCSS / W3C / JSON / Tailwind v4 config.
 *
 * Usage:
 *   bun export.ts --brand design/design.json --format <css-vars|scss|w3c|json|tailwind-v4> --output <path>
 *
 * Output MUST land outside the design store directory. Defaults per format:
 *   css-vars     → tokens.css
 *   scss         → _tokens.scss
 *   w3c          → tokens.json
 *   json         → brand.tokens.json
 *   tailwind-v4  → app.css   (CSS-first @theme block)
 *
 * Tailwind v4 emit uses an inline template scaffold + design.json substitution; any
 * dynamic roles the template doesn't anticipate are appended as an "extras" block.
 *
 * Tailwind v3 support has been dropped — the skill is v4-only.
 *
 * Exit 0 ok · 1 IO · 2 bad args.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";

type Format = "css-vars" | "scss" | "w3c" | "json" | "tailwind-v4";

const TAILWIND_V4_TEMPLATE = `/* Generated by studio. Source of truth: design/design.json.
 * Re-emit via: bun \${CLAUDE_SKILL_DIR}/scripts/design/export.ts \\
 *                --brand design/design.json --format tailwind-v4 --output app.css
 */
@import "tailwindcss";

@theme {
  --color-bg: {{COLOR_BG}};
  --color-fg: {{COLOR_FG}};
  --color-primary: {{COLOR_PRIMARY}};
  --color-primary-hover: {{COLOR_PRIMARY_HOVER}};
  --color-primary-active: {{COLOR_PRIMARY_ACTIVE}};
  --color-primary-disabled: {{COLOR_PRIMARY_DISABLED}};
  --color-primary-fg: {{COLOR_PRIMARY_FG}};
  --color-accent: {{COLOR_ACCENT}};
  --color-destructive: {{COLOR_DESTRUCTIVE}};
  --color-muted: {{COLOR_MUTED}};
  --color-muted-fg: {{COLOR_MUTED_FG}};
  --color-border: {{COLOR_BORDER}};
  --color-ring: {{COLOR_RING}};

  --font-display: {{FONT_DISPLAY}};
  --font-body: {{FONT_BODY}};
  --font-mono: {{FONT_MONO}};

  --text-sm: {{SIZE_SM}};
  --text-base: {{SIZE_BASE}};
  --text-lg: {{SIZE_LG}};
  --text-xl: {{SIZE_XL}};
  --text-2xl: {{SIZE_2XL}};
  --text-3xl: {{SIZE_3XL}};

  --spacing-1: {{SPACE_1}};
  --spacing-2: {{SPACE_2}};
  --spacing-3: {{SPACE_3}};
  --spacing-4: {{SPACE_4}};
  --spacing-6: {{SPACE_6}};
  --spacing-8: {{SPACE_8}};
  --spacing-12: {{SPACE_12}};

  --radius-sm: {{RADIUS_SM}};
  --radius-md: {{RADIUS_MD}};
  --radius-lg: {{RADIUS_LG}};
  --radius-pill: 9999px;

  --shadow-sm: {{SHADOW_SM}};
  --shadow-md: {{SHADOW_MD}};
  --shadow-lg: {{SHADOW_LG}};
}
`;

const argv = Bun.argv.slice(2);
const args: { brand?: string; format?: Format; output?: string } = {};
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === "--brand") args.brand = argv[++i];
  else if (a === "--format") args.format = argv[++i] as Format;
  else if (a === "--output") args.output = argv[++i];
  else if (a === "-h" || a === "--help") {
    console.log("Usage: bun export.ts --brand <path> --format <fmt> --output <path>");
    console.log("formats: css-vars | scss | w3c | json | tailwind-v4");
    process.exit(0);
  }
}
if (!args.brand || !args.format) { console.error("--brand and --format required"); process.exit(2); }

const ALLOWED_FORMATS: Format[] = ["css-vars", "scss", "w3c", "json", "tailwind-v4"];
if (!ALLOWED_FORMATS.includes(args.format!)) {
  console.error(`Unknown format: ${args.format}. Allowed: ${ALLOWED_FORMATS.join(" | ")}`);
  process.exit(2);
}

const defaultOutputs: Record<Format, string> = {
  "css-vars": "tokens.css", "scss": "_tokens.scss", "w3c": "tokens.json",
  "json": "brand.tokens.json", "tailwind-v4": "app.css"
};
const outPath = resolve(args.output ?? defaultOutputs[args.format!]);

const brandPath = resolve(args.brand);
if (!existsSync(brandPath)) { console.error(`Not found: ${brandPath}`); process.exit(1); }

const brandStoreDir = dirname(brandPath);
const normOutPath = outPath.endsWith("/") ? outPath.slice(0, -1) : outPath;
if (normOutPath === brandStoreDir || normOutPath.startsWith(brandStoreDir + "/")) {
  console.error(`Output MUST land outside the brand store directory (${brandStoreDir}).`);
  process.exit(2);
}

let brand: any;
try {
  brand = JSON.parse(readFileSync(brandPath, "utf-8"));
} catch (e) {
  console.error(`Invalid JSON in ${brandPath}: ${(e as Error).message}`);
  process.exit(1);
}

function emitCssVars(): string {
  const lines: string[] = [":root {"];
  for (const t of brand.tokens?.color ?? []) lines.push(`  --color-${t.role}: ${t.value};`);
  for (const t of brand.tokens?.typography ?? []) lines.push(`  --font-${t.role}: ${t.value};`);
  for (const t of brand.tokens?.spacing ?? []) lines.push(`  --space-${t.role}: ${t.value};`);
  for (const t of brand.tokens?.text_scale ?? []) lines.push(`  --text-${t.role}: ${t.value};`);
  for (const t of brand.tokens?.depth ?? []) lines.push(`  --${t.role}: ${t.value};`);
  for (const t of brand.tokens?.motion ?? []) lines.push(`  --${t.role}: ${t.value};`);
  lines.push("}");
  return lines.join("\n") + "\n";
}

function emitScss(): string {
  const lines: string[] = ["// Sass variables (compile-time)"];
  const mirror: string[] = [];
  for (const t of brand.tokens?.color ?? []) {
    lines.push(`$color-${t.role}: ${t.value};`);
    mirror.push(`  --color-${t.role}: #{$color-${t.role}};`);
  }
  for (const t of brand.tokens?.typography ?? []) {
    lines.push(`$font-${t.role}: ${t.value};`);
    mirror.push(`  --font-${t.role}: #{$font-${t.role}};`);
  }
  for (const cat of ["spacing", "text_scale", "depth", "motion"] as const) {
    for (const t of brand.tokens?.[cat] ?? []) {
      lines.push(`$${t.role}: ${t.value};`);
      mirror.push(`  --${t.role}: #{$${t.role}};`);
    }
  }
  lines.push("\n// Mirror as CSS custom properties for runtime use");
  lines.push(":root {");
  lines.push(...mirror);
  lines.push("}");
  return lines.join("\n") + "\n";
}

function emitW3c(): string {
  const out: any = { $schema: "https://design-tokens.github.io/community-group/format/" };
  out.color = {};
  for (const t of brand.tokens?.color ?? []) out.color[t.role] = { $value: t.value, $type: "color" };
  out.typography = {};
  for (const t of brand.tokens?.typography ?? []) out.typography[t.role] = { $value: t.value, $type: "fontFamily" };
  out.spacing = {};
  for (const t of brand.tokens?.spacing ?? []) out.spacing[t.role] = { $value: t.value, $type: "dimension" };
  out.text_scale = {};
  for (const t of brand.tokens?.text_scale ?? []) out.text_scale[t.role] = { $value: t.value, $type: "dimension" };
  out.depth = {};
  for (const t of brand.tokens?.depth ?? []) out.depth[t.role] = { $value: t.value, $type: String(t.role).startsWith("shadow") ? "shadow" : "dimension" };
  out.motion = {};
  for (const t of brand.tokens?.motion ?? []) out.motion[t.role] = { $value: t.value, $type: "duration" };
  return JSON.stringify(out, null, 2) + "\n";
}

function emitJson(): string {
  const flat: any = { color: {}, typography: {}, spacing: {}, text_scale: {}, depth: {}, motion: {} };
  for (const cat of Object.keys(flat) as Array<keyof typeof flat>) {
    for (const t of brand.tokens?.[cat] ?? []) flat[cat][t.role] = t.value;
  }
  return JSON.stringify(flat, null, 2) + "\n";
}

function emitTailwindV4(): string {
  const colorOf = (role: string) => brand.tokens?.color?.find((c: any) => c.role === role)?.value ?? "";
  const fontOf = (role: string) => brand.tokens?.typography?.find((c: any) => c.role === role)?.value ?? "";
  const spaceOf = (n: string) => brand.tokens?.spacing?.find((c: any) => c.role === `space-${n}` || c.role === n)?.value ?? "";
  const radiusOf = (s: string) => brand.tokens?.depth?.find((c: any) => c.role === `radius-${s}`)?.value ?? "";
  const shadowOf = (s: string) => brand.tokens?.depth?.find((c: any) => c.role === `shadow-${s}`)?.value ?? "";
  const sizeOf = (s: string, fallback: string) => brand.tokens?.text_scale?.find((c: any) => c.role === s)?.value ?? fallback;

  const subs: Record<string, string> = {
    COLOR_BG: colorOf("bg"),
    COLOR_FG: colorOf("fg"),
    COLOR_PRIMARY: colorOf("primary"),
    COLOR_PRIMARY_HOVER: colorOf("primary-hover"),
    COLOR_PRIMARY_ACTIVE: colorOf("primary-active"),
    COLOR_PRIMARY_DISABLED: colorOf("primary-disabled"),
    COLOR_PRIMARY_FG: colorOf("primary-fg"),
    COLOR_ACCENT: colorOf("accent"),
    COLOR_DESTRUCTIVE: colorOf("destructive"),
    COLOR_MUTED: colorOf("muted"),
    COLOR_MUTED_FG: colorOf("muted-fg"),
    COLOR_BORDER: colorOf("border"),
    COLOR_RING: colorOf("ring"),
    FONT_DISPLAY: fontOf("display"),
    FONT_BODY: fontOf("body"),
    FONT_MONO: fontOf("mono"),
    SIZE_SM: sizeOf("sm", "0.875rem"), SIZE_BASE: sizeOf("md", "1rem"), SIZE_LG: sizeOf("lg", "1.125rem"),
    SIZE_XL: sizeOf("xl", "1.25rem"), SIZE_2XL: sizeOf("2xl", "1.5rem"), SIZE_3XL: sizeOf("display", "1.875rem"),
    SPACE_1: spaceOf("1"), SPACE_2: spaceOf("2"), SPACE_3: spaceOf("3"),
    SPACE_4: spaceOf("4"), SPACE_6: spaceOf("6"), SPACE_8: spaceOf("8"), SPACE_12: spaceOf("12"),
    RADIUS_SM: radiusOf("sm"), RADIUS_MD: radiusOf("md"), RADIUS_LG: radiusOf("lg"),
    SHADOW_SM: shadowOf("sm"), SHADOW_MD: shadowOf("md"), SHADOW_LG: shadowOf("lg")
  };

  let rendered = TAILWIND_V4_TEMPLATE;
  for (const [k, v] of Object.entries(subs)) {
    rendered = rendered.replace(new RegExp(`\\{\\{${k}\\}\\}`, "g"), v);
  }
  // drop declarations whose token is absent — `--color-x: ;` is a Tailwind build error
  rendered = rendered.split("\n").filter(line => !/:\s*;\s*$/.test(line)).join("\n");

  // Append any dynamic color roles the template's vocabulary doesn't cover
  const knownRoles = new Set([
    "bg", "fg", "primary", "primary-hover", "primary-active", "primary-disabled", "primary-fg",
    "accent", "destructive", "muted", "muted-fg", "border", "ring"
  ]);
  const extras: string[] = [];
  for (const t of brand.tokens?.color ?? []) {
    if (!knownRoles.has(t.role)) extras.push(`  --color-${t.role}: ${t.value};`);
  }
  if (extras.length) {
    rendered = rendered.replace(/\}\s*$/, `\n  /* extras */\n${extras.join("\n")}\n}\n`);
  }
  return rendered;
}

const emit: Record<Format, () => string> = {
  "css-vars": emitCssVars,
  "scss": emitScss,
  "w3c": emitW3c,
  "json": emitJson,
  "tailwind-v4": emitTailwindV4
};

const output = emit[args.format!]();
writeFileSync(outPath, output);
console.log(JSON.stringify({ ok: true, format: args.format, output: outPath, bytes: output.length }, null, 2));
