#!/usr/bin/env bun
/**
 * init.ts — Scaffold design/ in the current project.
 *
 * Creates:
 *   <dir>/design.json        — empty per-schema canonical store
 *   <dir>/DESIGN.md          — human-readable summary (inline template)
 *   <dir>/drafts/            — for from-url / from-screenshot / from-moodboard drafts
 *   <dir>/reports/           — for drift-check outputs
 *   <dir>/.design-version    — schema $id pin
 * Appends inline gitignore snippet to project root .gitignore.
 * Idempotent: safe to re-run.
 *
 * Usage:
 *   bun init.ts --dir design [--schema <path>] [--no-gitignore] [--force]
 *
 * Only the schema lives as a separate asset (required by ajv compilation).
 * DESIGN.md template and gitignore snippet are inlined below for zero-asset slimness.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync } from "node:fs";
import { resolve, dirname, join } from "node:path";

const GITIGNORE_SNIPPET = `# studio design system — local-only artifacts (do not commit)
design/drafts/
design/.merge.lock
design/reports/
.studio/
`;

const DESIGN_MD_TEMPLATE = `# Design System

> Generated by the Studio skill at {{TIMESTAMP}}. Edit freely — this file is for humans. The machine-readable source of truth is \`design.json\`.

## Source

- **Origin:** {{SOURCE_URL or "manual / moodboard / screenshot"}}
- **Extraction mode:** {{EXTRACTION_MODE}}
- **Global confidence:** {{CONFIDENCE_GLOBAL}}
- **Last updated:** {{UPDATED_AT}}

## Palette

| Role | Value | Confidence |
|---|---|---|
| Background | \`{{COLOR_BG}}\` | {{CONF_BG}} |
| Foreground | \`{{COLOR_FG}}\` | {{CONF_FG}} |
| Primary | \`{{COLOR_PRIMARY}}\` | {{CONF_PRIMARY}} |
| Accent | \`{{COLOR_ACCENT}}\` | {{CONF_ACCENT}} |
| Destructive | \`{{COLOR_DESTRUCTIVE}}\` | {{CONF_DESTRUCTIVE}} |

Derived states (computed via \`scripts/design/derive-states.ts\`):

- Primary hover: \`{{COLOR_PRIMARY_HOVER}}\` · active: \`{{COLOR_PRIMARY_ACTIVE}}\` · disabled: \`{{COLOR_PRIMARY_DISABLED}}\` · fg: \`{{COLOR_PRIMARY_FG}}\`
- Muted fg: \`{{COLOR_MUTED_FG}}\` · Border: \`{{COLOR_BORDER}}\` · Ring: \`{{COLOR_RING}}\`

## Typography

- **Display:** \`{{FONT_DISPLAY}}\`
- **Body:** \`{{FONT_BODY}}\`
- **Mono:** \`{{FONT_MONO}}\`
- **Scale ratio:** {{SCALE_RATIO}}
- **Sizes:** {{SIZE_LADDER}}

## Spacing

Base unit: **{{BASE_UNIT}}px**. Scale: {{SPACING_SCALE}}.

## Radius

{{RADIUS_SCALE}} — buttons and inputs share \`{{RADIUS_BUTTON}}\`.

## Shadow

{{SHADOW_LANGUAGE}} — three-tier scale (sm / md / lg).

## Motion

- Easing: enter \`cubic-bezier(0, 0, 0.2, 1)\`, exit \`cubic-bezier(0.4, 0, 1, 1)\`
- Durations: hover 150ms · press 100ms · tooltip 200ms · modal 250–350ms · page 300–500ms
- \`prefers-reduced-motion\` honored

## Coverage flags

{{COVERAGE_FLAGS_BULLETS}}

## History

{{HISTORY_BULLETS}}
`;

interface Args {
  dir: string;
  schema?: string;
  noGitignore?: boolean;
  force?: boolean;
}

function help(): never {
  console.log(`Usage: bun init.ts --dir <path> [--schema <path>] [--no-gitignore] [--force]

Creates a design/ scaffold at the given dir with design.json, DESIGN.md, drafts/, reports/, .design-version.
By default appends an inline gitignore snippet to project .gitignore. Pass --no-gitignore to skip.
--schema defaults to the bundled design-system.schema.json next to the skill's assets/.`);
  process.exit(0);
}

const argv = Bun.argv.slice(2);
const args: Partial<Args> = {};
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === "--dir") args.dir = argv[++i];
  else if (a === "--schema") args.schema = argv[++i];
  else if (a === "--no-gitignore") args.noGitignore = true;
  else if (a === "--force") args.force = true;
  else if (a === "-h" || a === "--help") help();
  else { console.error(`Unknown flag: ${a}`); help(); }
}
if (!args.dir) help();

const assetsDir = resolve(import.meta.dir, "..", "..", "assets");
const schemaPath = resolve(args.schema ?? join(assetsDir, "design-system.schema.json"));

if (!existsSync(schemaPath)) { console.error(`Schema not found: ${schemaPath}`); process.exit(1); }

const brandDir = resolve(args.dir!);
const schemaRaw = readFileSync(schemaPath, "utf-8");
const schema = JSON.parse(schemaRaw);
const schemaVersion = schema.properties?.schema_version?.const ?? "0.1.0";
const schemaId: string = schema.$id ?? `local-schema-v${schemaVersion}`;

mkdirSync(brandDir, { recursive: true });
mkdirSync(join(brandDir, "drafts"), { recursive: true });
mkdirSync(join(brandDir, "reports"), { recursive: true });

const brandJsonPath = join(brandDir, "design.json");
if (!existsSync(brandJsonPath) || args.force) {
  const now = new Date().toISOString();
  const empty = {
    $schema: schemaId,
    schema_version: schemaVersion,
    source_url: null,
    fetched_at: null,
    updated_at: now,
    tokens: { color: [], typography: [], spacing: [], text_scale: [], motion: [], depth: [] },
    derived: { states: {}, contrast: [] },
    coverage_flags: { js_rendered: false, css_in_js_likely: false, theme_variants_found: [], responsive_variants_found: [] },
    confidence_global: 0,
    extraction_mode: "fast",
    history: [{ at: now, op: "init", summary: `scaffolded design store at ${args.dir}` }]
  };
  writeFileSync(brandJsonPath, JSON.stringify(empty, null, 2) + "\n");
}

const designPath = join(brandDir, "DESIGN.md");
if (!existsSync(designPath) || args.force) {
  const filled = DESIGN_MD_TEMPLATE.replace(/\{\{TIMESTAMP\}\}/g, new Date().toISOString());
  writeFileSync(designPath, filled);
}

const versionPath = join(brandDir, ".design-version");
writeFileSync(versionPath, `${schemaVersion}\n${schemaId}\n`);

let gitignoreStatus: "appended" | "already-present" | "skipped" = "skipped";
if (!args.noGitignore) {
  // project root = the invocation cwd, not dirname(brandDir) — `--dir a/b/design`
  // would otherwise write .gitignore into a/b/ instead of the repo root
  const projectRoot = process.cwd();
  const giPath = join(projectRoot, ".gitignore");
  const existing = existsSync(giPath) ? readFileSync(giPath, "utf-8") : "";
  if (existing.includes("studio design system")) {
    gitignoreStatus = "already-present";
  } else {
    appendFileSync(giPath, (existing.endsWith("\n") || existing === "" ? "" : "\n") + GITIGNORE_SNIPPET);
    gitignoreStatus = "appended";
  }
}

console.log(JSON.stringify({
  ok: true,
  brand_dir: brandDir,
  files: {
    design_json: brandJsonPath,
    design_md: designPath,
    version: versionPath,
    drafts_dir: join(brandDir, "drafts"),
    reports_dir: join(brandDir, "reports")
  },
  schema_version: schemaVersion,
  schema_id: schemaId,
  gitignore: gitignoreStatus
}, null, 2));
